### ISSUE TITLE
以发布日期排序文章，优先显示最新

### ISSUE THREAD

**Issue by itmowang** [wdssmq/blog-astro#5]

**Comment by wdssmq** [comment]
[up. 按时间排序 · wdssmq/blog-astro@9911d0a](https://github.com/wdssmq/blog-astro/commit/9911d0a548ac0c6db2da782b5c8015eed020ed1b "up. 按时间排序 · wdssmq/blog-astro@9911d0a")
↑ 也可以自定义排序函数
